server:
  port: 8080
  tempDirectory: F:\media\test

logging.level.org.springframework.web: DEBUG

spring:
  servlet:
    multipart:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.17:5432/lonelyproject?useSSL=false&amp
    username: lonelyproject
    password: lonelyproject
  ssl: false
  liquibase:
    default-schema: public

cdn:
  url: https://cdn.ryanoneil.me/file

backblaze:
  url: https://api001.backblazeb2.com
  buckets:
    avatars:
      id: a30266e75deeb3a3864f0b19
      name: lp-bucket

