server:
  port: 8080

logging.level.org.springframework.web: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.17:5432/lonelyproject?useSSL=false&amp
    username: lonelyproject
    password: lonelyproject
  ssl: false