name: Commit quality checks
on: [ push ]
jobs:
  build:
    name: Sonar
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        name: Setup Java environment
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven
      - name: Maven package
        run: mvn --update-snapshots verify
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          args: >
            -Dsonar.projectKey=${{ github.event.repository.name }}
            -Dsonar.branch.name=${{ github.ref_name }}
            -Dsonar.java.binaries=**/target/classes
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}