name: Run maven verify
on:
  workflow_call:
jobs:
  verify:
    name: Maven Verify
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        name: Setup Java environment
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Maven package
        run: /actions-runner/apache-maven-3.8.4/bin/mvn --batch-mode --update-snapshots verify